config/routes.rb
Icosmith::Application.routes.draw do

  post "/generate_font" => "font_generator#create"
  root to: 'home#index'

end

app/models/font_builder.rb
class FontBuilder

  attr_reader :manifest, :source_path, :build_path

  def initialize manifest, source_path
    @manifest = manifest
    @source_path = File.expand_path(source_path)
    @build_path = File.expand_path(File.join(@source_path, "build"))    
  end

  def build!
    FileUtils.mkdir_p(@build_path) unless File.exist?(@build_path)
    builder = self

    Blacksmith.forge do
      target builder.build_path
      source builder.source_path

      builder.header_keys.each do |key|
        value = builder.manifest[key]
        self.send(key, value) if value
      end

      builder.glyphs.each do |g|
        name = "#{g[:name]}.svg"
        glyph name, g
      end
    end

    generate_eot
  end

  def header_keys
    @manifest.keys.select {|key| Manifest::DEFAULT_MANIFEST.keys.include?(key)}
  end

  def glyphs
    @manifest[:glyphs]
  end

  private
  def generate_eot
    ttf_filename = Dir.entries(@build_path).find {|name| name =~ /\.ttf$/}
    eot_filename = ttf_filename.gsub(/\.ttf/, ".eot")
    cmd = "ttf2eot #{@build_path}/#{ttf_filename} > #{@build_path}/#{eot_filename}"
    puts cmd
    system cmd
  end

end

app/models/manifest.rb
class Manifest

  FILENAME = "manifest.json"
  FIRST_CHAR = 57345

  DEFAULT_MANIFEST = {
    name: nil,
    family: "FontSmith Font",
    weight: "Regular",
    ascent: 800,
    descent: 200,
    version: nil,
    copyright: "",
    baseline: nil,
    scale: nil,
    offset: nil
  }

  DEFAULT_GLYPH = {
    code: nil,
    name: nil,
    left_side_bearing: 15,
    right_side_bearing: 15,
    scale: nil,
    offset: nil
  }

  def initialize params = {}
    super params
  end

  def self.generate path
    hash = exist?(path) ? generate_by_file(path) : generate_new
    # font name needs to be the same as family name
    # to prevent IE8 from not rendering eot format
    hash[:name] = hash[:family]
    hash[:version] = (hash[:version] || "1").ljust(3, ".0")

    last_glyph = hash[:glyphs].last
    first_char = last_glyph ? last_glyph[:code] + 1 : FIRST_CHAR
    update_glyphs! hash, path, first_char

    hash
  end

  def self.exist? path
    File.exist?("#{path}/#{FILENAME}")
  end

  def self.read path
    JSON.parse(File.read("#{path}/#{FILENAME}")).deep_symbolize_keys
  end

  def self.get_svgs_from path, exclude = []
    Dir.entries(path).
      select {|f| f =~ /\.svg$/}.
      map {|f| f.gsub(/\.svg$/, '')}.
      reject {|name| exclude.include?(name)}
  rescue Errno::ENOENT
    []
  end

  def self.filter_to_save hash
    glyphs = hash.delete :glyphs
    result = {}

    (DEFAULT_MANIFEST.keys - [:baseline, :scale, :offset, :copyright]).each do |key|
      value = hash[key]
      result[key] = value if value
    end

    result[:copyright] = hash[:copyright] unless hash[:copyright].blank?
    result[:glyphs] = glyphs.map {|g| {code: "0x#{g[:code].to_s(16)}", name: g[:name]}}
    JSON.pretty_generate result
  end

  private
  def self.generate_by_file path
    hash = DEFAULT_MANIFEST.merge read(path)
    hash[:glyphs] = hash[:glyphs].map {|hash| new_glyph_by_hex(hash.deep_symbolize_keys)}
    hash
  end

  def self.generate_new
    hash = DEFAULT_MANIFEST
    hash[:glyphs] = []
    hash
  end

  def self.update_glyphs! hash, path, first_char
    char = first_char
    already_configured = hash[:glyphs].collect {|h| h[:name]}
    get_svgs_from(path, already_configured).each do |name|
      hash[:glyphs] << new_glyph(name, char)
      char += 1
    end
  end

  def self.new_glyph name, char
    DEFAULT_GLYPH.merge(name: name, code: char)
  end

  def self.new_glyph_by_hex hash
    code = hash[:code].to_i(16)
    DEFAULT_GLYPH.merge(hash.merge(code: code))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected
  def skip_session
    request.session_options[:skip] = true
  end

end

app/controllers/font_generator_controller.rb
require "zip_file_generator"

class FontGeneratorController < ApplicationController

  def create
    unless params[:base64zip].blank?
      file = Tempfile.open(["#{Time.now.to_i}", ".zip"], encoding: "ascii-8bit")
      file.write Base64.decode64(params[:base64zip])
      file.close # ensure the write, odd cases :/

      file_name = file.path.scan(/\/([^\/]+)$/).flatten.first
      dir_name = file.path.gsub(file_name, '').gsub(/\/$/, '')
      @temp_file = File.open(file.path)

    else
      file = params["file"]
      file_name = file.original_filename
      dir_name = file_name.gsub(/\.zip$/, '')
      @temp_file = file.tempfile
    end

    Dir.mktmpdir do |dir|
      upload_path = "#{dir}/#{dir_name}"
      unzip! @temp_file, upload_path

      manifest = Manifest.generate(upload_path)
      builder = FontBuilder.new(manifest, upload_path)

      builder.build!
      prepare_package! manifest, builder

      filename = zip_name(manifest)
      result_path = zip! upload_path, filename, builder

      send_file(result_path, {
        filename: filename,
        type: "application/zip",
        disposition: "attachment"
      })
    end
  ensure
    if @temp_file
      @temp_file.close
      @temp_file.unlink if @temp_file.respond_to?(:unlink)
    end
  end

  private
  def unzip! file, destination
    Zip::ZipFile.open(file) do |zip_file|

      zip_file.reject {|f| f.name =~ /^[_|\.]/}.each do |f|
        dir_path = File.dirname File.join(destination, f.name)
        FileUtils.mkdir_p(dir_path) unless File.exist?(dir_path)
        zip_file.extract(f, File.join(dir_path, f.name))
      end

    end
  end

  def zip! path, filename, builder
    diretory_to_zip = builder.build_path
    output_file = "#{path}/#{filename}"
    destination = "tmp/#{filename}"

    zip_file = ZipFileGenerator.new diretory_to_zip, output_file
    zip_file.write

    FileUtils.mv output_file, File.expand_path(File.join(Rails.root, destination))
    File.expand_path(destination)
  end

  def zip_name manifest
    return manifest[:filename] if manifest[:filename]
    "#{manifest[:name].parameterize}-v#{manifest[:version]}-#{Time.now.to_i}.zip"
  end

  def prepare_package! manifest, builder
    example_path = "#{builder.build_path}/example"
    example_css = File.join(File.expand_path(Rails.root), "app/templates/extra/bootstrap.min.css")
    fonts_path = "#{builder.build_path}/fonts"

    FileUtils.mkdir_p example_path
    FileUtils.mkdir_p fonts_path
    
    Dir.glob("#{builder.build_path}/*.{ttf,woff,svg,eot,afm}").each do |file|
      FileUtils.mv(file, fonts_path)
    end
    
    FileUtils.cp example_css, example_path
    FileUtils.mv Dir["#{builder.build_path}/*.html"].first, example_path
    File.open("#{builder.build_path}/manifest.json", "w") {|f| f.write(Manifest.filter_to_save(manifest))}
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    skip_session
    expires_in 15.minutes, public: true
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="row-fluid">

    <div class="info">
      <h3>what is this?</h3>
      <h4>IcoSmith is an open source icon font generator</h4>
    </div>

    <%= form_tag generate_font_url, id: "smith-upload", class: "dropzone" do %>
    <% end %>
    <%= form_tag generate_font_url, multipart: true, id: :b64upload do %>
      <input type="hidden" name="base64zip" value="">

      <span class="hint">
        <em>Only <strong>*.svg</strong> and the <strong>manifest.json</strong></em>
      </span>

      <div class="input-append">
        <input type="text" name="family" placeholder="Family name">

        <div class="input-append input-prepend">
          <input type="text" name="version" placeholder="version 1.0">
        </div>

        <input type="submit" id="send" class="btn" value="Generate Font!">
      </div>
    <% end %>

  </div>
</div>

<a href="https://github.com/tulios/icosmith" id="fork-me"><span>Fork me on GitHub</span></a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Icosmith</title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Lato" %>

    <%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" %>
    <%= javascript_include_tag "application" %>

    <%= csrf_meta_tags %>
    <meta property="og:title" content="IcoSmith"/>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content="http://www.icosmith.com"/>
    <meta property="og:site_name" content="IcoSmith"/>
    <meta property="og:description" content="IcoSmith is an open source icon font generator"/>
    <meta name="description" content="IcoSmith is an open source icon font generator" />
  </head>
  <body>

    <%= render partial: "shared/header" %>
    <%= yield %>
    <%= render partial: "shared/footer" %>

  </body>
</html>

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <section>
      <h1>MIT License</h1>

      <p>IcoSmith is licensed under MIT.</p>
      <p>Copyright (c) 2013 Túlio Ornelas</p>
    </section>

    <section>
      <p>Permission is hereby granted, free of charge, to any person obtaining a copy
      of this software and associated documentation files (the "Software"), to deal
      in the Software without restriction, including without limitation the rights
      to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
      copies of the Software, and to permit persons to whom the Software is
      furnished to do so, subject to the following conditions:</p>

      <p>The above copyright notice and this permission notice shall be included in all
      copies or substantial portions of the Software.</p>
    </section>

    <section>
      <p>THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
      AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
      OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
      SOFTWARE.</p>
    </section>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="navbar transparent navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="/"><strong>IcoSmith</strong></a>
      <div class="nav-collapse collapse">
        <ul class="nav pull-right"></ul>
      </div>
    </div>
  </div>
</div>